#!/bin/sh
#
# sleepy        Startup script for sleepy
#
# chkconfig: - 90 10
# processname: sleepy
# config: /etc/sleepy
# pidfile: /var/run/sleepy/sleepy.pid
# description: Sleepy is a web-application server.
#
### BEGIN INIT INFO
# Provides: sleepy
# Required-Start: $local_fs $remote_fs $network
# Required-Stop: $local_fs $remote_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop sleepy
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

prog=sleepy
sleepy=${SLEEPY-/usr/bin/sleepyd}
lockfile=${LOCKFILE-/var/lock/subsys/sleepy}
pidfile=${PIDFILE-/var/run/sleepy/sleepy.pid}
RETVAL=0

start() {
    echo -n $"Starting $prog: "

    daemon --pidfile=${pidfile} "nohup ${sleepy} >/dev/null 2>&1 &"
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && touch ${lockfile}
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p ${pidfile} ${prog}
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
}

rh_status() {
    status -p ${pidfile} ${sleepy}
}

# See how we were called.
case "$1" in
    start)
        rh_status >/dev/null 2>&1 && exit 0
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        rh_status
        RETVAL=$?
        ;;
    *)
        echo $"Usage: $prog {start|stop|restart|status|help}"
        RETVAL=2
esac

exit $RETVAL
